### PR TITLE
Add jekyll-glossary_tooltip

### PR DESCRIPTION
**Pull request by erikw**

### CODE REVIEW

**Review by jeffreytse — COMMENTED** [review]
Thanks for the contribution👍🏻

**Comment by erikw** [comment]
@jeffreytse thank you for looking at the PR!

I wonder, how is this README.md deployed to https://planetjekyll.github.io/plugins/. Does it have to manually built in https://github.com/planetjekyll/planetjekyll.github.io and deployed or is there a CD setup?

**Comment by geraldb** [comment]
Sorry for some time (years) this page doesn't get updated - yes, it was done manually with a script, see <https://github.com/yorobot/planetjekyll>.

**Comment by jeffreytse** [comment]
@erikw You're welcome, you can follow the answer by @geraldb. : )

**Pull request merged**
